---
- name: Copy update-exim4.conf.conf
  template: src=update-exim4.j2
            dest=/etc/exim4/update-exim4.conf.conf mode=0664 owner=root
            group=root
  notify:
    - restart exim4

- name: Copy /etc/default/exim4
  template: src=exim4.j2 dest=/etc/default/exim4 mode=0644 owner=root group=root
  notify:
    - restart exim4

- name: Configure hubbed hosts
  template: src=hubbed_hosts.j2 dest=/etc/exim4/hubbed_hosts
  when: exim4_hubbed_hosts is defined
  notify:
    - restart exim4

- name: Copy localmacros
  template:
    src: localmacros.j2
    dest: /etc/exim4/conf.d/main/000_localmacros
  notify:
    - restart exim4

- name: Copy modified acl file check_rcpt
  template:
    src: 30_exim4-config_check_rcpt.j2
    dest: /etc/exim4/conf.d/acl/30_exim4-config_check_rcpt
  when: exim4_is_smarthost
  notify:
    - restart exim4

- name: Copy modified smtp smarthost transport config
  template:
    src: 30_exim4-config_remote_smtp_smarthost.j2
    dest: /etc/exim4/conf.d/transport/30_exim4-config_remote_smtp_smarthost
  when: exim4_use_client_certificates
  notify:
    - restart exim4

- name: Copy smtp smarthost partial transport config
  template:
    src: 160_exim4-config_smarthost_partial.j2
    dest: /etc/exim4/conf.d/router/160_exim4-config_smarthost_partial
  when: exim4_partial_smarthost_percentage > 0
  notify:
    - restart exim4

- name: Copy email-addresses
  template:
    src: email-addresses.j2
    dest: /etc/email-addresses
  notify:
    - restart exim4
