---

- name: Stop sendmail
  service: name=sendmail state=stopped
  ignore_errors: yes

- name: Uninstall sendmail
  apt:
    state: absent
    name:
      - sendmail
      - sendmail-base
      - sendmail-bin
      - sendmail-cf
